# 1. Read JSON file

We use the Python library [Pandas](http://pandas.pydata.org) to read the dataset, which is given in [JSON](http://json.org) format:

In [1]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df = pd.read_json('data/challenge.json')
df.shape

(204428, 14)

In [3]:
df.head()

branch_id  customer_code  group_code  is_churn  item_code  \
0          0            143           0       0.0        854   
1          0            433           0       0.0        246   
2          0            486           0       0.0       1420   
3          0            107           0       0.0       1963   
4          0            768           0       0.0       1786   

   item_total_price  order_id  quantity         register_date  sales_channel  \
0            292.91     21804        10  2017-11-10T00:00:00Z              0   
1            287.19      5486        20  2011-05-16T00:00:00Z              1   
2            184.84     22662        12  2018-01-24T00:00:00Z              0   
3            189.18      3956        18  2010-07-28T00:00:00Z              1   
4             66.87      4730         5  2010-12-17T00:00:00Z              1   

   segment_code  seller_code  total_price  unit_price  
0             0          190      1613.53       25.04  
1             5          153     11163.69       12.33  
2             0          166      6432.12       12.80  
3             0          156       831.82       10.51  
4             0          218      1736.48       11.82

In [4]:
df.nunique()

branch_id               1
customer_code         838
group_code              4
is_churn                2
item_code            2981
item_total_price    55336
order_id            24618
quantity              290
register_date        3121
sales_channel         106
segment_code            8
seller_code           290
total_price         22713
unit_price          19828
dtype: int64

The dataset contains **24618** orders from **838** clients.

# 2. Time Series Analysis

In [5]:
df["year_month"] = pd.to_datetime(df.register_date.str.slice(0, 7))

In [6]:
df.year_month.value_counts().sort_index().plot(figsize=(15, 5))
plt.xlabel("year")
plt.ylabel("orders")
plt.title("Number of orders");